<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-RLSB6HV" failures="1" tests="2" name="Test" time="27.069" errors="0" timestamp="2024-06-22T15:14:45 IST">
  <testcase classname="com.Test.LoginPageTest" name="valid" time="2.775"/>
  <testcase classname="com.Test.LoginPageTest" name="Check_OptionCount_and_data" time="5.12">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [4] but found [6]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [4] but found [6]
at com.Test.LoginPageTest.Check_OptionCount_and_data(LoginPageTest.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Check_OptionCount_and_data -->
  <testcase classname="com.Test.LoginPageTest" name="validCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- validCredentials -->
  <testcase classname="com.Test.LoginPageTest" name="invalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- invalidCredentials -->
</testsuite> <!-- Test -->
